# Generated by Django 5.2.8 on 2025-11-13 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info_Model',
            fields=[
                ('Student_Add_no', models.CharField(max_length=50, unique=True)),
                ('Student_Name', models.CharField(max_length=250, unique=True)),
                ('Student_Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Student_Phone', models.CharField(max_length=15)),
                ('Student_Father', models.CharField(max_length=250)),
                ('Student_Address', models.CharField(max_length=250)),
                ('Student_Img', models.ImageField(upload_to='student/')),
                ('user_Stn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wing_Model',
            fields=[
                ('Wing_Code', models.CharField(max_length=50, unique=True)),
                ('Wing_Name', models.CharField(max_length=250, unique=True)),
                ('Wing_Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Chair_Person', models.CharField(max_length=15)),
                ('Assist_Person', models.CharField(max_length=15)),
                ('wing_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
