# Generated by Django 5.2.8 on 2025-11-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Add_no', models.CharField(max_length=50, unique=True)),
                ('Student_Name', models.CharField(max_length=250)),
                ('Student_Email', models.EmailField(max_length=254, unique=True)),
                ('Student_Phone', models.CharField(max_length=15)),
                ('Student_Position', models.CharField(max_length=100)),
                ('Student_Goal', models.CharField(blank=True, max_length=250, null=True)),
                ('Student_Dob', models.DateField(default='2010-08-10')),
                ('Student_Father', models.CharField(max_length=250)),
                ('Student_Address', models.CharField(max_length=250)),
                ('Student_Img', models.ImageField(upload_to='student_Box/')),
                ('Total_Achievements', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_OutReachs', models.IntegerField(blank=True, default=0, null=True)),
                ('ShaadMaan_Total', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_Anjuman', models.IntegerField(blank=True, default=0, null=True)),
                ('user_Stn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wing_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wing_Code', models.CharField(max_length=50, unique=True)),
                ('Wing_Name', models.CharField(max_length=250, unique=True)),
                ('Wing_Email', models.EmailField(max_length=254, unique=True)),
                ('wing_logo', models.ImageField(upload_to='wing_Box/')),
                ('Total_Registered', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_ReSulted', models.IntegerField(blank=True, default=0, null=True)),
                ('Assist_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_in_wings', to='admin_panel.student_model')),
                ('Chair_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairPerson_in_wings', to='admin_panel.student_model')),
                ('wing_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
