# Generated by Django 5.2.8 on 2025-11-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grallery_model',
            name='Created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model'),
        ),
    ]
