# Generated by Django 5.2.8 on 2025-11-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_grallery_model_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grallery_model',
            name='Created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model'),
        ),
    ]
