# Generated by Django 5.2.8 on 2025-11-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_grallery_model_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wing_model',
            name='Total_Programed',
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_AnjumanHudaPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_Anjuman_e_Huda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_ClassPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_ClassProgrames',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_ClassProgramesPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_OutReachPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_ReSulted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_Registered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_SelfCreationPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Total_Self_Creations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
