# Generated by Django 5.2.8 on 2025-11-29 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_wing_model_total_programed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='Total_ClassPoints',
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='Total_Class_Anjuman',
        ),
        migrations.CreateModel(
            name='Gallery_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_Title', models.CharField(max_length=300)),
                ('Gallery_Files', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('Gallery_Vedio', models.FileField(blank=True, null=True, upload_to='Vedio/')),
                ('Gallery_Dic', models.TextField(max_length=500)),
                ('Created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
        migrations.DeleteModel(
            name='Grallery_Model',
        ),
    ]
