# Generated by Django 5.2.8 on 2025-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_student_model_total_classpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='is_Controller',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
