# Generated by Django 5.2.8 on 2025-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_student_model_is_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='is_Controller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
