# Generated by Django 5.2.8 on 2025-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_student_model_is_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='Tatal_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_AnjumanHudaPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_Anjuman_e_Huda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_ClassProgrames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_ClassProgramesPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_OutReachPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_OutReachs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_ReSulted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_Registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_SelfCreationPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='Total_Self_Creations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wing_model',
            name='Total_ReSulted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wing_model',
            name='Total_Registered',
            field=models.IntegerField(default=0),
        ),
    ]
