# Generated by Django 5.2.8 on 2025-11-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_name', models.CharField(max_length=200)),
                ('Program_Venue', models.CharField(max_length=250)),
                ('Program_date', models.DateField(auto_now=True)),
                ('Program_poster', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('Program_Created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates_Registration_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidates_Name', models.CharField(max_length=230)),
                ('wing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
                ('Registered_Programe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wing_panel.program_bank')),
            ],
        ),
    ]
