# Generated by Django 5.2.8 on 2025-11-24 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_name', models.CharField(max_length=200)),
                ('Program_Venue', models.CharField(max_length=250)),
                ('Program_date', models.DateField(default=django.utils.timezone.now)),
                ('Program_poster', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('is_Registration', models.BooleanField(blank=True, default=True, null=True)),
                ('is_Resulted', models.BooleanField(blank=True, default=False, null=True)),
                ('Program_Created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates_Registration_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidates_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model')),
                ('Registered_Programe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wing_panel.program_bank')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Bank_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_Holder1_img', models.ImageField(blank=True, null=True, upload_to='Resulted_img/')),
                ('Position_Holder2_img', models.ImageField(blank=True, null=True, upload_to='Resulted_img/')),
                ('Position_Holder3_img', models.ImageField(blank=True, null=True, upload_to='Resulted_img/')),
                ('Secure_Grade', models.CharField(blank=True, default='No Grade', null=True)),
                ('Result_Baner', models.FileField(blank=True, null=True, upload_to='Results/')),
                ('Grande_Holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grande_Holder', to='wing_panel.candidates_registration_model')),
                ('Position_Holder1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_holder_1', to='wing_panel.candidates_registration_model')),
                ('Position_Holder2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_holder_2', to='wing_panel.candidates_registration_model')),
                ('Position_Holder3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_holder_3', to='wing_panel.candidates_registration_model')),
                ('Result_Programe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wing_panel.program_bank')),
                ('Result_Uploaded_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
    ]
