# Generated by Django 5.2.8 on 2025-11-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('program_date', models.DateField()),
                ('program_poster', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('program_disc', models.TextField(max_length=500)),
                ('program_Created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wing_panel.program')),
                ('students', models.ManyToManyField(to='admin_panel.student_model')),
                ('wing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.wing_model')),
            ],
        ),
    ]
