# Generated by Django 5.2.8 on 2025-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_bank',
            name='Tatal_Registrations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
