# Generated by Django 5.2.8 on 2025-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing_panel', '0002_program_bank_tatal_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_bank',
            name='Tatal_Registrations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
