# Generated by Django 5.2.8 on 2025-11-22 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing_panel', '0003_upload_result_position_holder1_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_bank',
            name='Program_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
