# Generated by Django 5.2.8 on 2025-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing_panel', '0006_alter_result_bank_model_grande_holder_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_bank',
            name='Tatal_Registrations',
            field=models.IntegerField(default=0),
        ),
    ]
