# Generated by Django 5.2.8 on 2025-12-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing_panel', '0009_alter_result_bank_model_secure_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_bank',
            name='Program_Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program_bank',
            name='is_Registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='program_bank',
            name='is_Resulted',
            field=models.BooleanField(default=False),
        ),
    ]
