# Generated by Django 5.2.8 on 2025-11-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_Title', models.CharField(max_length=250)),
                ('achiever_Result', models.CharField(max_length=250)),
                ('achieveMent_Conductor', models.CharField(max_length=500)),
                ('achieveMent_date', models.DateField()),
                ('achieveMent_poster', models.ImageField(blank=True, null=True, upload_to='AchieveMents/')),
                ('achieveMent_discription', models.TextField(max_length=600)),
                ('Total_Achievements', models.IntegerField(default=0)),
                ('Achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model')),
            ],
        ),
        migrations.CreateModel(
            name='OutReach_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OutReach_Programe_name', models.CharField(max_length=250)),
                ('OutReach_result', models.CharField(max_length=250)),
                ('OutReach_Conductor', models.CharField(max_length=500)),
                ('OutReach_date', models.DateField()),
                ('OutReach_poster', models.ImageField(blank=True, null=True, upload_to='OutReach/')),
                ('OutReach_discription', models.TextField(max_length=600)),
                ('Total_OutReach', models.IntegerField(default=0)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model')),
            ],
        ),
    ]
