# Generated by Django 5.2.8 on 2025-11-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_Title', models.CharField(max_length=250)),
                ('resulted', models.CharField(max_length=250)),
                ('achieveMent_Conductor', models.CharField(max_length=500)),
                ('achieveMent_date', models.DateField()),
                ('achieveMent_poster', models.ImageField(blank=True, null=True, upload_to='AchieveMents/')),
                ('achieveMent_discription', models.TextField(max_length=600)),
                ('Achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model')),
            ],
        ),
        migrations.CreateModel(
            name='OutReach_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programe_name', models.CharField(max_length=250)),
                ('result', models.CharField(max_length=250)),
                ('programe_Conductor', models.CharField(max_length=500)),
                ('programe_date', models.DateField()),
                ('programe_poster', models.ImageField(blank=True, null=True, upload_to='OutReach/')),
                ('programe_discription', models.TextField(max_length=600)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_model')),
            ],
        ),
    ]
