# Generated by Django 5.2.8 on 2025-11-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_student_model_total_classpoints_and_more'),
        ('students_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements_Model',
            new_name='Ajnumame_Huda_Model',
        ),
    ]
