# Generated by Django 5.2.8 on 2025-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements_model',
            name='Total_Achievements',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
