# Generated by Django 5.2.8 on 2025-12-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_panel', '0002_rename_achievements_model_ajnumame_huda_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajnumame_huda_model',
            name='Total_Achievements',
            field=models.IntegerField(default=0),
        ),
    ]
