# Generated by Django 5.2.8 on 2025-11-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_panel', '0002_alter_achievements_model_total_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach_model',
            name='Total_OutReach',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
