# Generated by Django 6.0 on 2025-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_panel', '0003_alter_ajnumame_huda_model_total_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach_model',
            name='Point_ForThis',
            field=models.IntegerField(default=0),
        ),
    ]
