# Generated by Django 6.0 on 2025-12-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_panel', '0004_outreach_model_point_forthis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajnumame_huda_model',
            old_name='Total_Achievements',
            new_name='Point_ForThis',
        ),
    ]
